#!/bin/sh

echo "Running pre-push checks..."

# Task 1. Run tests
echo "Running all tests..."
mvn test

if [ $? -ne 0 ]; then
  echo "Tests have failed. Push has been aborted."
  exit 1
fi

echo "Running dependency check vulnerability scan (OWASP)"

REPO_PATH=$(pwd -W)

#MSYS_NO_PATHCONV=1 docker run --rm \
#  --mount "type=bind,source=$REPO_PATH,target=/src" \
#  owasp/dependency-check:latest \
#  --scan /src \
#  --disableCentral \
#  --format HTML \
#  --out /dependency-check/report

if [ $? -ne 0 ]; then
    echo "Dependency check scan has failed. Push has been aborted."
    exit 1
fi

echo "Pre-push checks have passed successfully."
exit 0