FROM jenkins/jenkins:lts

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    docker.io \
    python3 \
    python3-pip \
    nmap \
    sqlmap \
    curl \
    wget \
    default-jre \
    procps && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install semgrep --break-system-packages

RUN wget https://github.com/zaproxy/zaproxy/releases/download/v2.15.0/ZAP_2_15_0_Linux.tar.gz \
    && tar -xzf ZAP_2_15_0_Linux.tar.gz -C /opt \
    && rm ZAP_2_15_0_Linux.tar.gz \
    && chmod +x /opt/zap/zap.sh

ENV PATH="/opt/zap:$PATH"

USER jenkins