FROM jenkins/jenkins:lts

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    docker.io \
    python3 \
    python3-pip \
    nmap \
    sqlmap \
    curl \
    wget \
    default-jre \
    procps && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install semgrep --break-system-packages

RUN wget -O zap.tar.gz https://github.com/zaproxy/zaproxy/releases/download/v2.17.0/ZAP_2.17.0_Linux.tar.gz \
    && mkdir -p /opt/zap \
    && tar -xzf zap.tar.gz -C /opt/zap --strip-components=1 \
    && rm zap.tar.gz \
    && chmod +x /opt/zap/zap.sh

ENV PATH="/opt/zap:$PATH"

USER jenkins