sonar.projectKey=electronic-book-records
sonar.projectName=electronic-book-records

sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.java.binaries=target/classes
sonar.exclusions=**/target/**,**/generated/**